### ISSUE TITLE
incorrect instructions

### ISSUE THREAD

**Issue by JosephDSmith** [learn-co-curriculum/p3-oo-one-to-many-lab#1]
### Canvas Link

https://learning.flatironschool.com/courses/6208/assignments/240334?module_item_id=565027

### Concern

the instructions say:

In the Owner class write a method called sort_pets_by_name(self) returns a sorted list of pets by their names.

the test uses differenct criteria:

Owner' object has no attribute 'get_sorted_pets'

Also, this should be a code-grade submission, not a URL submission 

### Suggested Changes

the test should match the method syntax in the instructions

**Comment by linda-seiter** [comment]
Fixed #3
