### ISSUE TITLE
Solution code needed

### ISSUE THREAD

**Issue by will-chang6** [learn-co-curriculum/p3-oo-one-to-many-lab#2]
### Canvas Link

https://learning.flatironschool.com/courses/6462/assignments/246582?module_item_id=581563

### Concern

Can the solution code be provided for this lab? 
Also, the lesson doesn't adequately prepare for this lab... there are missing knowledge that can't be inferred through logic.

**Comment by will-chang6** [comment]
I'm able to see the solution code now.

**Comment by linda-seiter** [comment]
Fixed #4
